apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mssql"
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mssql-cm
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    
    [coredump]
    captureminiandfull = true
    coredumptype = full
    
    [hadr]
    hadrenabled = 1
    
    [language]
    lcid = 1033
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: "mssql"
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
        env:
        - name: MSSQL_PID
          value: express
        - name: ACCEPT_EULA
          value: "y"
        - name: MSSQL_AGENT_ENABLED
          value: "false"
        - name: SA_PASSWORD
          value: p@ssw0rd
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: 2Gi
        volumeMounts:
        - name: mssql-data  
          mountPath: /var/opt/mssql
        - name: mssql-config
          mountPath: /var/opt/config
      volumes:
      - name: mssql-config
        configMap:
          name: mssql-cm
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
