apiVersion: v1
data:
  update_run.sh: |-
    # This script is required to run kafka cluster (without zookeeper)
    #!/bin/sh

    # Docker workaround: Remove check for KAFKA_ZOOKEEPER_CONNECT parameter
    sed -i '/KAFKA_ZOOKEEPER_CONNECT/d' /etc/confluent/docker/configure

    # Docker workaround: Ignore cub zk-ready
    sed -i 's/cub zk-ready/echo ignore zk-ready/' /etc/confluent/docker/ensure

    # KRaft required step: Format the storage directory with a new cluster ID
    echo "kafka-storage format --ignore-formatted -t $(kafka-storage random-uuid) -c /etc/kafka/kafka.properties" >> /etc/confluent/docker/ensure
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: kafka0
  name: kafka0-cm0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka0
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka0
    spec:
      containers:
        - args:
            - bash
            - -c
            - 'if [ ! -f /tmp/update_run.sh ]; then echo "ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka0:29093
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_JMX_OPTS
              value: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
            - name: KAFKA_JMX_PORT
              value: "9997"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_LOG_DIRS
              value: /tmp/kraft-combined-logs
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
          image: confluentinc/cp-kafka:7.2.1
          name: kafka0
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9997
              protocol: TCP
            - containerPort: 29092
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/update_run.sh
              name: kafka0-cm0
              subPath: update_run.sh
      hostname: kafka0
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: update_run.sh
                path: update_run.sh
            name: kafka0-cm0
            defaultMode: 0777
          name: kafka0-cm0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "9997"
      port: 9997
      targetPort: 9997
  selector:
    io.kompose.service: kafka0
